### ISSUE TITLE
Table 不能设置整体居中

### ISSUE THREAD

**Issue by zzyper** [sheinsight/shineout#182]
要在 columns 上一个个设置。如果在 Table 上设置 style={{ textAlign: 'center' }}，单元格居中，但是表头未居中。

![image](https://user-images.githubusercontent.com/26628346/58072620-d8134180-7bd2-11e9-945b-0606f4a8159d.png)

**Comment by EastblueOkay** [comment]
@zzyper 您好，感谢对`shineout`的支持。
> 在Table上设置 style ，可能会存在某些样式被覆盖导致没有效果（例如`textAlign:center`）。

建议您为Table设置className，通过`css`来设置布局方式：
```javascript
<Table className="myTable" {...otherProps} />
```
```css
.myTable table {
    th, td {
        text-align: center;
    }
}
```
